import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Headers } from "@/shared/components/Headers";
import { Hero } from "@/shared/components/Hero";
import { Banks } from "@/shared/components/Banks";
import { TradePro } from "@/shared/components/TradePro";
import { LastInfo } from "@/shared/components/LastInfo";
import { DownHeader } from "@/shared/components/DownHeader";
const inter = Inter({ subsets: ["latin"] });
// const mBanks = {{BankImg: "dsdsd"}};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script src="https://unpkg.com/@phosphor-icons/web"></script>
      </head>
      <body className={`${inter.className} antialiased`}>
        <Headers />
        <Hero />
        <Banks />
        <TradePro />
        <LastInfo />
        <DownHeader />
        {/* {mBanks.map(
      ({BankImg}) => (<Banks BankImg={BankImg}/>))}
        <div>{children}</div> */}
      </body>
    </html>
  );
}
